site_name: Best Python Practices
nav:
  - Home: index.md
  - Design Patterns: design_patterns.md
  - Tutorials:
      - Overview: tutorials.md
      - Performance:
          - Lookup Tables: tutorials/performance/lookup_tables.md
          - Profiling Tools & Strategy: tutorials/performance/profiling_tools.md
          - Multi-Processing: tutorials/performance/multiprocessing.md
      - Packaging:
          - Structure: tutorials/packaging/structure.md
          - Makefile: tutorials/packaging/makefile.md
          - Logging: tutorials/packaging/logging.md
          - Code Style: tutorials/packaging/code_style.md
          - API Design: tutorials/packaging/api_design.md
          - Anti Patterns: tutorials/packaging/anti_patterns.md
          - Testing: tutorials/packaging/testing.md
  - Libraries & Tools: libraries.md
  - Pull Requests Etiquette: pullrequests.md

repo_name: 'best-python-practices'
repo_url: 'https://github.com/felixgao/python-best-practices'

theme:
  name: material
  logo: assets/python.svg
  favicon: assets/python.svg

  # features:
  #   - header.autohide

  custom_dir: overrides
  
  palette:
    - scheme: default
      primary: indigo
      accent: yello

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list

extra:
  social:
    - icon: 'octicons/mark-github-16'
      link: 'https://github.com/felixgao/python-best-practices/'
